routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['web']], function(){
    Route::get('/blog/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+');
    Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);
    Route::get('/', 'PagesController@index');
    Route::get('/contact', 'ContactController@getContact');
    Route::post('/contact', 'ContactController@postContact');
    Route::resource('/posts', 'PostController');
    Route::resource('/blogcategories', 'BlogcategoryController', ['except' => ['create']]);
    Route::resource('/blogtags', 'BlogtagController', ['except' => ['create']]);
    Route::resource('/sliders', 'SliderController');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public function blogcategories()
    {
        return $this->belongsToMany('App\Blogcategory');
    }

    public function blogtags()
    {
    	return $this->belongsToMany('App\Blogtag');
    }
    public function postsphotos()
    {
        return $this->hasMany('App\PostsPhoto');
    }
    public function pics(){
        return $this->hasMany(Pic::class);
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use Session;
use App\Blogcategory;
use App\Blogtag;
use Image;
use Storage;
use File;
use App\PostsPhoto;
class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::orderBy('id', 'desc')->paginate(5);
        // return $posts;
        return view('posts.index')->withPosts($posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $blogcategories = Blogcategory::all();
        $blogtags = Blogtag::all();
        return view('posts.create')->withBlogcategories($blogcategories)->withBlogtags($blogtags);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate data
        $this->validate($request, array(
            'title'         => 'required|min:2|max:255',
            'body'          => 'required|min:15',
            'slug'          => 'required|alpha_dash|min:5|max:255|unique:posts,slug',
            'photo'         => 'image|mimes:jpeg,bmp,png,jpg|size:3072'
            // 'category_id'   => 'required|integer'
        ));
        //store in database
        $post = new Post;
        $post->title = $request->title;
        $post->body = $request->body;
        $post->slug = $request->slug;
        // $post->category_id = $request->category_id;

        if ($request->hasFile('featured_img')) {
            $image = $request->file('featured_img');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('images/' . $filename);
            Image::make($image)->fit(200)->save($location);
            $post->image = $filename;
          }


        $post->save();
        $post->blogtags()->sync($request->blogtags, false);
        $post->blogcategories()->sync($request->blogcategories, false);

        if ($request->hasFile('photos')){
            foreach ($request->photos as $photo) {
            $filenameWithExt = $photo->getClientOriginalName();
            $filename = $filenameWithExt.time() . '.' . $photo->getClientOriginalExtension();
            $location = public_path('images/' . $filename);
            Image::make($photo)->fit(200)->save($location);
            PostsPhoto::create([
                'post_id' => $post->id,
                'filename' => $filename
                ]);
                }
            }
        Session::flash('success', 'مطلب شما ایجاد شد');
        return redirect()->route('posts.show', $post->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        $photos =PostsPhoto::with('Post')->find($id);
        return view ('posts.show', compact('post', 'photos'));
        // return $post;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        $blogcategories = Blogcategory::all();
        $cats2 = array();
        foreach ($blogcategories as $blogcategory) {
            $cats2[$blogcategory->id] = $blogcategory->name;
        }
        $blogtags = Blogtag::all();
        $blogtags2 = array();
        foreach ($blogtags as $blogtag) {
            $blogtags2[$blogtag->id] = $blogtag->name;
        }
        return view('posts.edit')->withPost($post)->withBlogcategories($cats2)->withBlogtags($blogtags2);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::find($id);
        if ($request->input('slug') == $post->slug) {
            $this->validate($request, array(
                'title' => 'required|min:2|max:255',
                'body'  => 'required|min:15',
                // 'category_id' => 'required|integer'
            ));
        } else {
        $this->validate($request, array(
            'title'         => 'required|min:2|max:255',
            'body'          => 'required|min:15',
            'slug'          => 'required|alpha_dash|min:5|max:255|unique:posts,slug',
            // 'category_id' => 'required|integer'
        ));
    }

        $post = Post::find($id);
        $post->title = $request->input('title');
        $post->body = $request->input('body');
        $post->slug = $request->input('slug');
        // $post->category_id = $request->input('category_id');

        if($request->hasFile('featured_img')) {
            $image = $request->file('featured_img');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('images/' . $filename);
            Image::make($image)->fit(200)->save($location);

            $oldFilename = $post->image;

            $post->image = $filename;

            File::delete('images/' .$oldFilename);
        }

        $post->save();
        if (isset($request->blogtags)) {
            $post->blogtags()->sync($request->blogtags);
        } else {
            $post->blogtags()->sync(array());
        }

        if (isset($request->blogcategories)) {
            $post->blogcategories()->sync($request->blogcategories);
        } else {
            $post->blogcategories()->sync(array());
        }

        if ($request->hasFile('photos')){
            // PostsPhoto::where('post_id', $id)->delete();
            foreach ($request->photos as $photo) {
            $filenameWithExt = $photo->getClientOriginalName();
            $filename = $filenameWithExt.time() . '.' . $photo->getClientOriginalExtension();
            $location = public_path('images/' . $filename);
            Image::make($photo)->fit(200)->save($location);
            PostsPhoto::create([
                'post_id' => $post->id,
                'filename' => $filename
                ]);
                }
        }


        Session::flash('success', 'مطلب شما بروزرسانی شد');
        return redirect()->route('posts.show', $post->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        $post->blogtags()->detach();
        $post->blogcategories()->detach();
        $photos = PostsPhoto::where('post_id', $id)->get();
        foreach($photos as $photo){
            File::delete('images/' .$photo->filename);
        }
        PostsPhoto::where('post_id', $id)->delete();
        File::delete('images/' .$post->image);

        $post->delete();

        Session::flash('success', 'مطلب شما حذف شد');
        return redirect()->route('posts.index');
    }
}

resources/views/posts/create.blade.php
@extends('main')

@section('title', '| Create New Post')

@section('stylesheets')

	{!! Html::style('css/parsley.css') !!}
	{!! Html::style('css/select2.min.css') !!}
	<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>

	<script>
		tinymce.init({
			selector: 'textarea',
			plugins: 'link code',
			menubar: false
		});
	</script>

@endsection

@section('content')

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1>ایجاد یک مطلب جدید</h1>
			<hr>
			{!! Form::open(array('route' => 'posts.store', 'data-parsley-validate' => '', 'files' => true)) !!}
				{{ Form::label('title', 'عنوان') }}
				{{ Form::text('title', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '255')) }}

				{{ Form::label('slug', 'تکه آدرس URL') }}
				{{ Form::text('slug', null, array('class' => 'form-control', 'required' => '', 'minlength' => '5', 'maxlength' => '255') ) }}

				{{-- {{ Form::label('category_id', 'Category:') }}
				<select class="form-control" name="category_id">
					@foreach($categories as $category)
						<option value='{{ $category->id }}'>{{ $category->name }}</option>
					@endforeach
				</select> --}}

				{{ Form::label('categories', 'دسته بندی:') }}
				<select class="form-control select2-multi" name="blogcategories[]" multiple="multiple">
					@foreach($blogcategories as $blogcategory)
						<option value='{{ $blogcategory->id }}'>{{ $blogcategory->name }}</option>
					@endforeach

				</select>


				{{ Form::label('tags', 'Tags:') }}
				<select class="form-control select2-multi" name="blogtags[]" multiple="multiple">
					@foreach($blogtags as $blogtag)
						<option value='{{ $blogtag->id }}'>{{ $blogtag->name }}</option>
					@endforeach

				</select>

				{{ Form::label('featured_img', 'Upload a Featured Image') }}
				{{ Form::file('featured_img') }}

				{{ Form::label('photos', 'Other Image') }}
				{{ Form::file('photos[]', ['multiple' => 'multiple']) }}


				{{ Form::label('body', "محتوا") }}
				{{ Form::textarea('body', null, array('class' => 'form-control')) }}

				{{ Form::submit('Create Post', array('class' => 'btn btn-success btn-lg btn-block', 'style' => 'margin-top: 20px;')) }}
			{!! Form::close() !!}
		</div>
	</div>

@endsection


@section('scripts')

	{!! Html::script('js/parsley.min.js') !!}
	{!! Html::script('js/select2.min.js') !!}
	<script type="text/javascript">
		$('.select2-multi').select2();
	</script>

@endsection

resources/views/posts/edit.blade.php
@extends('main')

@section('title', '| Edit Blog Post')

@section('stylesheets')

	{!! Html::style('css/select2.min.css') !!}

	<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>

	<script>
		tinymce.init({
			selector: 'textarea',
			plugins: 'link code',
			menubar: false
		});
	</script>

@endsection

@section('content')

	<div class="row">
		{!! Form::model($post, ['route' => ['posts.update', $post->id], 'method' => 'PUT', 'files' => true]) !!}
		<div class="col-md-8">
			{{ Form::label('title', 'عنوان:') }}
			{{ Form::text('title', null, ["class" => 'form-control input-lg']) }}

			{{ Form::label('slug', 'Slug:', ['class' => 'form-spacing-top']) }}
			{{ Form::text('slug', null, ['class' => 'form-control']) }}

			{{ Form::label('featured_img', 'Upload a Featured Image') }}
            {{ Form::file('featured_img') }}

            {{ Form::label('photos', 'Other Image') }}
			{{ Form::file('photos[]', ['multiple' => 'multiple']) }}

			{{-- {{ Form::label('category_id', "Category:", ['class' => 'form-spacing-top']) }}
			{{ Form::select('category_id', $categories, null, ['class' => 'form-control']) }} --}}

			{{ Form::label('categories', 'دسته بندی:', ['class' => 'form-spacing-top']) }}
			{{ Form::select('blogcategories[]', $blogcategories, null, ['class' => 'form-control select2-multi', 'multiple' => 'multiple']) }}

			{{ Form::label('tags', 'Tags:', ['class' => 'form-spacing-top']) }}
			{{ Form::select('blogtags[]', $blogtags, null, ['class' => 'form-control select2-multi', 'multiple' => 'multiple']) }}

			{{ Form::label('body', "محتوا:", ['class' => 'form-spacing-top']) }}
			{{ Form::textarea('body', null, ['class' => 'form-control']) }}
		</div>

		<div class="col-md-4">
			<div class="well">
				<dl class="dl-horizontal">
					<dt>ایجاد شده در:</dt>
					<dd>{{ date('M j, Y h:ia', strtotime($post->created_at)) }}</dd>
				</dl>

				<dl class="dl-horizontal">
					<dt>آخرین تغییرات:</dt>
					<dd>{{ date('M j, Y h:ia', strtotime($post->updated_at)) }}</dd>
				</dl>
				<hr>
				<div class="row">
					<div class="col-sm-6">
						{!! Html::linkRoute('posts.show', 'لغو', array($post->id), array('class' => 'btn btn-danger btn-block')) !!}
					</div>
					<div class="col-sm-6">
						{{ Form::submit('ذخیره تغییرات', ['class' => 'btn btn-success btn-block']) }}
					</div>
				</div>

			</div>
		</div>
		{!! Form::close() !!}
	</div>	<!-- end of .row (form) -->

@stop

@section('scripts')

	{!! Html::script('js/select2.min.js') !!}

	<script type="text/javascript">
		$('.select2-multi').select2();
	</script>

@endsection

resources/views/posts/index.blade.php
@extends('main')

@section('title', '| All Posts')

@section('content')

	<div class="row">
		<div class="col-md-10">
			<h1>همه مطالب</h1>
		</div>

		<div class="col-md-2">
			<a href="{{ route('posts.create') }}" class="btn btn-lg btn-block btn-primary">ایجاد</a>
		</div>
		<div class="col-md-12">
			<hr>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<table class="table">
				<thead>
					<th>#</th>
					<th>عنوان</th>
					<th>محتوا</th>
					<th>تاریج ایجاد</th>
					<th></th>
				</thead>

				<tbody>
					
					@foreach ($posts as $post)
						
						<tr>
							<th>{{ $post->id }}</th>
							<td>{{ $post->title }}</td>
							<td>{{ substr(strip_tags($post->body), 0, 50) }}{{ strlen(strip_tags($post->body)) > 50 ? "..." : "" }}</td>
							<td>{{ date('M j, Y', strtotime($post->created_at)) }}</td>
							<td><a href="{{ route('posts.show', $post->id) }}" class="btn btn-default btn-sm">View</a> <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-default btn-sm">Edit</a></td>
						</tr>

					@endforeach

				</tbody>
			</table>

			<div class="text-center">
				{!! $posts->links(); !!}
			</div>
		</div>
	</div>

@stop

resources/views/posts/show.blade.php
@extends('main')

@section('title', '| View Post')

@section('content')

	<div class="row">
		<div class="col-md-8">
			<h1>{{ $post->title }}</h1>

			<p class="lead">{!! $post->body !!}</p>

			<hr>

			<div class="tags">
				@foreach ($post->blogtags as $blogtag)
					<span class="label label-default"><a href="{{ route('blogtags.show', $blogtag->id) }}">{{ $blogtag->name }}</a></span>
				@endforeach
			</div>
		<img src="{{asset('/images/' . $post->image)}}" alt="">
		<hr>
        @foreach($post->postsphotos as $photo)
            <img src="{{asset('/images/' . $photo->filename)}}">
        @endforeach
		<hr>

			{{-- <div id="backend-comments" style="margin-top: 50px;">
				<h3>Comments <small>{{ $post->comments()->count() }} total</small></h3>

				<table class="table">
					<thead>
						<tr>
							<th>Name</th>
							<th>Email</th>
							<th>Comment</th>
							<th width="70px"></th>
						</tr>
					</thead>

					<tbody>
						@foreach ($post->comments as $comment)
						<tr>
							<td>{{ $comment->name }}</td>
							<td>{{ $comment->email }}</td>
							<td>{{ $comment->comment }}</td>
							<td>
								<a href="{{ route('comments.edit', $comment->id) }}" class="btn btn-xs btn-primary"><span class="glyphicon glyphicon-pencil"></span></a>
								<a href="{{ route('comments.delete', $comment->id) }}" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div> --}}
		</div>

		<div class="col-md-4">
			<div class="well">
				<dl class="dl-horizontal">
					<label>Url:</label>
					<p><a href="{{ url('blog/'.$post->slug) }}">{{ url('blog/'.$post->slug) }}</a></p>
				</dl>

				<div class="tags">
					@foreach ($post->blogcategories as $blogcategory)
						<span class="label label-default"><a href="{{ route('blogcategories.show', $blogcategory->id) }}">{{ $blogcategory->name }}</a></span>
					@endforeach
				</div>

				{{-- <dl class="dl-horizontal">
					<label>دسته بندی:</label>
					<p><a href="{{ route('categories.show', $post->category->id) }}" class="btn btn-default btn-sm">{{ $post->category->name }}</a></p>
					<label>توضیح دسته بندی: </label>
					<p>{{ $post->category->body }}</p>
				</dl> --}}

				<dl class="dl-horizontal">
					<label>ایجاد شده در:</label>
					<p>{{ date('M j, Y h:ia', strtotime($post->created_at)) }}</p>
					<label>ایجاد شده در:</label>
					<p>{{ $post->created_at }}</p>
				</dl>

				<dl class="dl-horizontal">
					<label>آخرین بروزرسانی:</label>
					<p>{{ date('Y-m-d H:i:s', strtotime($post->updated_at)) }}</p>
				</dl>
				<hr>
				<div class="row">
					<div class="col-sm-6">
						{!! Html::linkRoute('posts.edit', 'Edit', array($post->id), array('class' => 'btn btn-primary btn-block')) !!}
					</div>

					<div class="col-sm-6">
						{!! Form::open(['route' => ['posts.destroy', $post->id], 'method' => 'DELETE']) !!}

							{!! Form::submit('Delete', ['class' => 'btn btn-danger btn-block']) !!}

						{!! Form::close() !!}
					</div>
				</div>

				{{-- <div class="row">
					<div class="col-md-12">
						{{ Html::linkRoute('posts.index', '<< See All Posts', array(), ['class' => 'btn btn-default btn-block btn-h1-spacing']) }}
					</div>
				</div> --}}

			</div>
		</div>
	</div>

@endsection