routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['web']], function(){
    Route::get('/blog/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+');
    Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);
    Route::get('/', 'PagesController@index');
    Route::get('/contact', 'ContactController@getContact');
    Route::post('/contact', 'ContactController@postContact');
    Route::resource('/posts', 'PostController');
    Route::resource('/blogcategories', 'BlogcategoryController', ['except' => ['create']]);
    Route::resource('/blogtags', 'BlogtagController', ['except' => ['create']]);
    Route::resource('/sliders', 'SliderController');
});

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    //
}

app/Http/Controllers/SliderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Slider;
use Session;
use Image;
use File;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sliders = Slider::paginate(5);
        return view('slider.index',compact('sliders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('slider.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
            'title'         => 'required|min:2|max:255',
            'link'          => 'max:255',
        ));
        //store in database
        $slider = new Slider;
        $slider->title = $request->title;
        $slider->body = $request->body;
        $slider->link = $request->link;

        if ($request->hasFile('featured_img')) {
            $image = $request->file('featured_img');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('slider/' . $filename);
            Image::make($image)->resize(50, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save($location);
            $slider->image = $filename;
          }

        $slider->save();
        Session::flash('success', 'اسلایدر ساخته شد');
        return redirect()->route('sliders.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $slider = Slider::find($id);
        return view('slider.edit',compact('slider'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $slider = Slider::find($id);
        $this->validate($request, array(
            'title'         => 'required|min:2|max:255',
            'link'          => 'max:255',
        ));

        $slider->title = $request->input('title');
        $slider->body = $request->input('body');
        $slider->link = $request->input('link');

        if($request->hasFile('featured_img')) {
            $image = $request->file('featured_img');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('slider/' . $filename);
            Image::make($image)->resize(50, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save($location);

            $oldFilename = $slider->image;

            $slider->image = $filename;

            File::delete('slider/' .$oldFilename);
        }

        $slider->save();
        Session::flash('success', 'اسلایدر بروزرسانی شد');
        return redirect()->route('sliders.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $slider = Slider::find($id);
        File::delete('slider/' .$slider->image);
        $slider->delete();

        Session::flash('success', 'اسلایدر شما حذف شد');
        return redirect()->route('sliders.index');
    }
}

resources/views/slider/create.blade.php
@extends('main')

@section('title', '| Create New Slider')

@section('stylesheets')

	<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>

	<script>
		tinymce.init({
			selector: 'textarea',
			plugins: 'link code',
			menubar: false
		});
	</script>

@endsection

@section('content')

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1>ایجاد یک اسلاید</h1>
			<hr>
			{!! Form::open(array('route' => 'sliders.store', 'data-parsley-validate' => '', 'files' => true)) !!}
				{{ Form::label('title', 'عنوان') }}
				{{ Form::text('title', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '255')) }}

				{{ Form::label('link', 'لینک ارجاع') }}
				{{ Form::text('link', null, array('class' => 'form-control')) }}

				{{ Form::label('featured_img', 'تصویر اسلایدر') }}
				{{ Form::file('featured_img') }}

				{{ Form::label('body', "محتوا") }}
				{{ Form::textarea('body', null, array('class' => 'form-control')) }}

				{{ Form::submit('ایجاد اسلایدر', array('class' => 'btn btn-success btn-lg btn-block', 'style' => 'margin-top: 20px;')) }}
			{!! Form::close() !!}
		</div>
	</div>

@endsection

resources/views/slider/edit.blade.php
@extends('main')

@section('title', '| Edit Slider')

@section('stylesheets')

	<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>

	<script>
		tinymce.init({
			selector: 'textarea',
			plugins: 'link code',
			menubar: false
		});
	</script>

@endsection

@section('content')

	<div class="row">
		{!! Form::model($slider, ['route' => ['sliders.update', $slider->id], 'method' => 'PUT', 'files' => true]) !!}
		<div class="col-md-8">
			{{ Form::label('title', 'عنوان:') }}
			{{ Form::text('title', null, ["class" => 'form-control input-lg']) }}

			{{ Form::label('link', 'لینک ارجاع:', ['class' => 'form-spacing-top']) }}
			{{ Form::text('link', null, ['class' => 'form-control']) }}

			{{ Form::label('featured_img', 'تصویر') }}
			{{ Form::file('featured_img') }}

			{{ Form::label('body', "محتوا:", ['class' => 'form-spacing-top']) }}
			{{ Form::textarea('body', null, ['class' => 'form-control']) }}
		</div>

		<div class="col-md-4">
			<div class="well">
				<dl class="dl-horizontal">
					<dt>ایجاد شده در:</dt>
					<dd>{{ date('M j, Y h:ia', strtotime($slider->created_at)) }}</dd>
				</dl>

				<dl class="dl-horizontal">
					<dt>آخرین تغییرات:</dt>
					<dd>{{ date('M j, Y h:ia', strtotime($slider->updated_at)) }}</dd>
				</dl>
				<hr>
				<div class="row">
					<div class="col-sm-6">
						{!! Html::linkRoute('sliders.index', 'لغو', array($slider->id), array('class' => 'btn btn-danger btn-block')) !!}
					</div>
					<div class="col-sm-6">
						{{ Form::submit('ذخیره تغییرات', ['class' => 'btn btn-success btn-block']) }}
					</div>
				</div>

			</div>
		</div>
		{!! Form::close() !!}
	</div>

@stop

@section('scripts')

	<script type="text/javascript">
		$('.select2-multi').select2();
	</script>

@endsection

resources/views/slider/index.blade.php
@extends('main')

@section('title', '| Sliders')

@section('content')

	<div class="row">
		<div class="col-md-10">
			<h1>اسلایدر</h1>
		</div>

		<div class="col-md-2">
			<a href="{{ route('sliders.create') }}" class="btn btn-lg btn-block btn-primary">ایجاد یک اسلایدر</a>
		</div>
		<div class="col-md-12">
			<hr>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<table class="table">
				<thead>
                    <th>#</th>
                    <th>تصویر</th>
					<th>عنوان</th>
                    <th>محتوا</th>
                    <th>لینک</th>
					<th>تاریج ایجاد</th>
					<th></th>
				</thead>

				<tbody>

					@foreach ($sliders as $slider)

						<tr>
                            <th>{{ $slider->id }}</th>
                            <td><img src="{{asset('/slider/' . $slider->image)}}" alt=""></td>
							<td>{{ $slider->title }}</td>
                            <td>{{ substr(strip_tags($slider->body), 0, 50) }}{{ strlen(strip_tags($slider->body)) > 50 ? "..." : "" }}</td>
                            <td>{{ $slider->link }}</td>
							<td>{{ date('M j, Y', strtotime($slider->created_at)) }}</td>
							<td>
                                {{ Form::open(['route' => ['sliders.destroy', $slider->id], 'method' => 'DELETE']) }}
                                    {{ Form::submit('حذف', ['class' => 'btn btn-danger btn-block']) }}
                                {{ Form::close() }}
                                 <a href="{{ route('sliders.edit', $slider->id) }}" class="btn btn-default btn-sm">ویرایش</a>
                            </td>
						</tr>

                    @endforeach


				</tbody>
			</table>

			<div class="text-center">
				{!! $sliders->links(); !!}
			</div>
		</div>
	</div>

@stop